title: "[General] <Title>"
labels: ["general"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check the docs!
        Before proceeding, please check these links for general help:
         - [Differences from Ethereum](https://era.zksync.io/docs/dev/building-on-zksync/contracts/differences-with-ethereum.html)
         - [Fee mechanism](https://era.zksync.io/docs/dev/developer-guides/transactions/fee-model.html)
         - [FAQ](https://docs.zksync.io/build/support/faq.html)

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Testnet
        - Mainnet
    validations:
      required: true
      
  - type: textarea
    id: functionality-description
    attributes:
      label: Provide a brief description of the functionality you're trying to implement and the issue you are running into.
    validations:
      required: true

  - type: input
    id: repo-link
    attributes:
      label: Repo Link (Optional)
      description: Though not mandatory, sharing a repository link with a README that details how to replicate the issue and the errors you're encountering will significantly expedite our support process.
    validations:
      required: false
      
  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: If applicable, please provide any additional details
    validations:
      required: false
